In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('answer1.csv')
df

,file_name,bbox,image_id,race,age,emotion,gender,skintone,masked
0,42777651.jpg,"[681, 1192, 210, 194]",336,mongoloid,20-30s,happiness,female,mid-light,unmasked
1,64419591.jpg,"[988, 320, 316, 393]",834,mongoloid,kid,neutral,female,mid-light,unmasked
2,88179407.jpg,"[1417, 324, 193, 273]",1614,caucasian,20-30s,happiness,male,mid-light,unmasked
3,image_2603.jpg,"[239, 154, 539, 858]",1850,caucasian,20-30s,happiness,male,mid-light,unmasked
4,69044640.jpg,"[792, 311, 470, 596]",975,caucasian,20-30s,neutral,female,mid-light,unmasked
...,...,...,...,...,...,...,...,...,...
2205,83587904.jpg,"[361, 319, 393, 474]",1478,caucasian,baby,fear,female,light,unmasked
2206,59309272.jpg,"[1282, 129, 156, 216]",643,caucasian,20-30s,neutral,male,light,unmasked
2207,54846073.jpg,"[1036, 203, 165, 222]",559,caucasian,senior,neutral,male,mid-light,unmasked
2208,60313342.jpg,"[412, 691, 188, 227]",675,caucasian,20-30s,happiness,male,mid-light,unmasked
2209,61565007.jpg,"[895, 165, 189, 279]",715,negroid,20-30s,neutral,male,mid-light,unmasked

In [3]:
s = 'asdasd'
s.title()

'Asdasd'

In [4]:
df['race'] = df['race'].apply(lambda x: x.title())
df['age'] = df['age'].apply(lambda x: x.title())
df['emotion'] = df['emotion'].apply(lambda x: x.title())
df['gender'] = df['gender'].apply(lambda x: x.title())
df

,file_name,bbox,image_id,race,age,emotion,gender,skintone,masked
0,42777651.jpg,"[681, 1192, 210, 194]",336,Mongoloid,20-30S,Happiness,Female,mid-light,unmasked
1,64419591.jpg,"[988, 320, 316, 393]",834,Mongoloid,Kid,Neutral,Female,mid-light,unmasked
2,88179407.jpg,"[1417, 324, 193, 273]",1614,Caucasian,20-30S,Happiness,Male,mid-light,unmasked
3,image_2603.jpg,"[239, 154, 539, 858]",1850,Caucasian,20-30S,Happiness,Male,mid-light,unmasked
4,69044640.jpg,"[792, 311, 470, 596]",975,Caucasian,20-30S,Neutral,Female,mid-light,unmasked
...,...,...,...,...,...,...,...,...,...
2205,83587904.jpg,"[361, 319, 393, 474]",1478,Caucasian,Baby,Fear,Female,light,unmasked
2206,59309272.jpg,"[1282, 129, 156, 216]",643,Caucasian,20-30S,Neutral,Male,light,unmasked
2207,54846073.jpg,"[1036, 203, 165, 222]",559,Caucasian,Senior,Neutral,Male,mid-light,unmasked
2208,60313342.jpg,"[412, 691, 188, 227]",675,Caucasian,20-30S,Happiness,Male,mid-light,unmasked
2209,61565007.jpg,"[895, 165, 189, 279]",715,Negroid,20-30S,Neutral,Male,mid-light,unmasked

In [5]:
df.to_csv('answer.csv', index=False)